### ISSUE TITLE
Double Right clicking?

### ISSUE THREAD

**Issue by Rain288** [isalin/TBbard#1]
Greetings.
So I just stumbled upon this utility recently and decided to give it a go today. While it does work great with selecting the instrument from the midi and stuff, for some reason I think the script double right clicks sometimes. 
I tried increasing the wait multiplier but I couldn't find any multiplier that would make it not double right click on certain parts. I also had a look at the code and to me it seems like it would only right click once per note instruction so neither can I deduce what the issue might be from that.
I also looked at what the text output of the midi import was and it did match the correct notes and waiting times for the  track I am trying to get it to play.
So I am quite lost as to why it is double clicking some notes.
Is there any chance you might have a hunch as to what it would be? I am trying to play [this](https://github.com/isalin/TBbard/files/1649898/double.right.clicking.zip) MIDI file, if you would want to test it yourself.
If you ever do take your time to view this issue and reply, thank you for taking that time, in advance! The utility is great otherwise.

**Comment by isalin** [comment]
I don't suppose you know at what timestamp the double clicking happens?

**Comment by Rain288** [comment]
Hopefully! I am going to test this later today probably and report back.
Sorry for not providing a time stamp of where the double clicking would be happening but I have been quite busy and did not have the chance to get into FFXIV and test around after I posted my github issue.
Thank you so much for looking into this so quickly and implementing a solution, much appreciated!

**Comment by Rain288** [comment]
I just tested it and it works perfectly now, thank you very much for creating this utility and fixing it per my request in such a short amount of time!
