### ISSUE TITLE
Songs that used to play fine now don't.

### ISSUE THREAD

**Issue by Snugglesffxi** [isalin/TBbard#15]
The old version stopped working for me so I downloaded the new one, awesome new features :D!
I'm having a problem with many songs that used to work properly before not working correctly now. In some cases it won't play certain "tracks" of the song. Like a the string or harp part of the song will play but if you select something else it won't play that specific part, when it used to before. Other times it completely skips notes and increases speed exponentially. 

Not sure if I need to be doing something different or if the octave target is just the wrong one I'm picking vs before... I can't seem to get anything to play correctly and have checked fps/timings/keyboard assignments. If it helps any most of the songs play incredibly fast now and I need to adjust the wait timer often and severely to compensate to get any decent melodies out.

**Comment by isalin** [comment]
No worries, I'm glad it worked out!
