### ISSUE TITLE
Can't open it

### ISSUE THREAD

**Issue by Marmeladenguru** [isalin/TBbard#21]
Heyo,

I can't run the program. When Im using Java to run TBbard, it isn't opening something. A glimpse of a cmd comes and closes immediately.
please help :/

**Comment by isalin** [comment]
If you hold down shift and right-click in the folder with the TBbard_v1.12.jar file, and then select "Open powershell here" or "Open console here". And then type "java -jar TBbard_v1.12.jar" in the console window. What does that say?
