### ISSUE TITLE
Can't get songs to play in game

### ISSUE THREAD

**Issue by squeegybee** [isalin/TBbard#23]
Hi there,

So I have everything installed, I put my midi file into the player, opened perform and selected an instrument, tbard says the song is playing but it's not playing in-game. 

Any advice?

**Comment by isalin** [comment]
Are you running it as admin?

**Comment by squeegybee** [comment]
Hi Isalin,

To the best of my knowledge I'm running it as an admin. My user is set to admin, and I'm not sure if there are any other steps beyond that. (Please note, I'm on a mac and I know jack sh*t about java lol)

**Comment by isalin** [comment]
Ah, right! I've not actually tested it on a mac!

Unfortunately, it's possible it just won't work on a mac :(

If you start a song and switch to a text document instead of ffxiv. Does it send the key presses there instead?

**Comment by squeegybee** [comment]
The key presses do not get sent to the text document. 

Does that mean it just doesn't work with mac? ;__;

**Comment by isalin** [comment]
Yeah, that seems to be the case. Sorry! :(

Unfortunately, I don't have a mac to try and test it on at the moment.

**Comment by squeegybee** [comment]
Ok, well if there's ever a future in which you do get a mac version working, please let me know!!

Thanks <3

**Comment by isalin** [comment]
I will!

Thanks for testing it out. And sorry it didn't work for you.

**Comment by squeegybee** [comment]
I appreciate your help! (If I feel the deep desire to rock out, I can always steal my husband's computer lol)
