### ISSUE TITLE
Doesn't work for me (Only in FFXIV)

### ISSUE THREAD

**Issue by RayofRage** [isalin/TBbard#3]
Hi,
just tested your program and it didn't work for me in FFXIV.
I have the standard layout and tested this also in a text editor. In the editor the Keys are pressed correctly but not in FFXIV.
If you ever look into this Thanks in advance for this program and your work.

**Comment by isalin** [comment]
It doesn’t input anything at all to ffxiv? 

Also, weird question, but have you tried restarting the game?

**Comment by RayofRage** [comment]
Yes it doesn't input anything into FFXIV.
Yup already tried to restart the game. Didn't change anything.

**Comment by isalin** [comment]
Weird. Could you try running it via a command prompt and copy/paste the output for me?

You can just shift+right click in the folder where TBbard is and select open command prompt (or something like that) and type “java -jar TBbard_1.3.jar”.

**Comment by RayofRage** [comment]
Sure here it is. But everything looks fine to me there.
[Log.txt](https://github.com/isalin/TBbard/files/1756090/Log.txt)

**Comment by isalin** [comment]
I agree, that looks like it should be working. Would you mind trying to run it as admin? 

If you unzip this batch file in the same folder as TBbard you should be able to rightclick it and select "Run as Administrator". Check of it then works with ffxiv

[TBbard.zip](https://github.com/isalin/TBbard/files/1756099/TBbard.zip)

**Comment by RayofRage** [comment]
Yes! That worked. Thank you. Seems like you need to run it sometimes as admin.

**Comment by RayofRage** [comment]
So now i tried to copy a midi file into it and that doesn't work now.

Sorry for reopening the case.

**Comment by isalin** [comment]
Alright. I've added a button to open a file using a dialog the traditional way. Would you mind testing it?
[TBbard_v1.3.jar.zip](https://github.com/isalin/TBbard/files/1756151/TBbard_v1.3.jar.zip)

**Comment by RayofRage** [comment]
Yes that works perfectly fine. Thank you for your work.
