### ISSUE TITLE
new release

### ISSUE THREAD

**Issue by kritanaz** [isalin/TBbard#6]
I don't understand how to use the master, are you going to compile into a release anytime soon?

**Comment by isalin** [comment]
Ah, sorry. Life's been busy over the past couple of days. 

I was going to wait until I'd added support for the new keyboard layouts. I also feel like the "long notes" sound a bit odd sometimes, but that might just be ffxiv's fault.

Here's a compiled preview version if you want to try it out!
[TBbard_v1.7-preview.zip](https://github.com/isalin/TBbard/files/2038442/TBbard_v1.7-preview.zip)

**Comment by kritanaz** [comment]
thanks so much! i've worked wityh your program a lot, it's great
